/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VentasRouteImport } from './routes/ventas'
import { Route as SoporteRouteImport } from './routes/soporte'
import { Route as SincronizacionRouteImport } from './routes/sincronizacion'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as OfflineDemoRouteImport } from './routes/offline-demo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as CajaRouteImport } from './routes/caja'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VentasDetalleRouteImport } from './routes/ventas.detalle'
import { Route as InventarioNuevoRouteImport } from './routes/inventario.nuevo'

const VentasRoute = VentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => rootRouteImport,
} as any)
const SoporteRoute = SoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => rootRouteImport,
} as any)
const SincronizacionRoute = SincronizacionRouteImport.update({
  id: '/sincronizacion',
  path: '/sincronizacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineDemoRoute = OfflineDemoRouteImport.update({
  id: '/offline-demo',
  path: '/offline-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const CajaRoute = CajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VentasDetalleRoute = VentasDetalleRouteImport.update({
  id: '/detalle',
  path: '/detalle',
  getParentRoute: () => VentasRoute,
} as any)
const InventarioNuevoRoute = InventarioNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => InventarioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/caja': typeof CajaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dashboard': typeof DashboardRoute
  '/inventario': typeof InventarioRouteWithChildren
  '/login': typeof LoginRoute
  '/offline-demo': typeof OfflineDemoRoute
  '/reportes': typeof ReportesRoute
  '/sincronizacion': typeof SincronizacionRoute
  '/soporte': typeof SoporteRoute
  '/ventas': typeof VentasRouteWithChildren
  '/inventario/nuevo': typeof InventarioNuevoRoute
  '/ventas/detalle': typeof VentasDetalleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/caja': typeof CajaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dashboard': typeof DashboardRoute
  '/inventario': typeof InventarioRouteWithChildren
  '/login': typeof LoginRoute
  '/offline-demo': typeof OfflineDemoRoute
  '/reportes': typeof ReportesRoute
  '/sincronizacion': typeof SincronizacionRoute
  '/soporte': typeof SoporteRoute
  '/ventas': typeof VentasRouteWithChildren
  '/inventario/nuevo': typeof InventarioNuevoRoute
  '/ventas/detalle': typeof VentasDetalleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/caja': typeof CajaRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dashboard': typeof DashboardRoute
  '/inventario': typeof InventarioRouteWithChildren
  '/login': typeof LoginRoute
  '/offline-demo': typeof OfflineDemoRoute
  '/reportes': typeof ReportesRoute
  '/sincronizacion': typeof SincronizacionRoute
  '/soporte': typeof SoporteRoute
  '/ventas': typeof VentasRouteWithChildren
  '/inventario/nuevo': typeof InventarioNuevoRoute
  '/ventas/detalle': typeof VentasDetalleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/caja'
    | '/configuracion'
    | '/dashboard'
    | '/inventario'
    | '/login'
    | '/offline-demo'
    | '/reportes'
    | '/sincronizacion'
    | '/soporte'
    | '/ventas'
    | '/inventario/nuevo'
    | '/ventas/detalle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/caja'
    | '/configuracion'
    | '/dashboard'
    | '/inventario'
    | '/login'
    | '/offline-demo'
    | '/reportes'
    | '/sincronizacion'
    | '/soporte'
    | '/ventas'
    | '/inventario/nuevo'
    | '/ventas/detalle'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/caja'
    | '/configuracion'
    | '/dashboard'
    | '/inventario'
    | '/login'
    | '/offline-demo'
    | '/reportes'
    | '/sincronizacion'
    | '/soporte'
    | '/ventas'
    | '/inventario/nuevo'
    | '/ventas/detalle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  CajaRoute: typeof CajaRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  DashboardRoute: typeof DashboardRoute
  InventarioRoute: typeof InventarioRouteWithChildren
  LoginRoute: typeof LoginRoute
  OfflineDemoRoute: typeof OfflineDemoRoute
  ReportesRoute: typeof ReportesRoute
  SincronizacionRoute: typeof SincronizacionRoute
  SoporteRoute: typeof SoporteRoute
  VentasRoute: typeof VentasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ventas': {
      id: '/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof VentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soporte': {
      id: '/soporte'
      path: '/soporte'
      fullPath: '/soporte'
      preLoaderRoute: typeof SoporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sincronizacion': {
      id: '/sincronizacion'
      path: '/sincronizacion'
      fullPath: '/sincronizacion'
      preLoaderRoute: typeof SincronizacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline-demo': {
      id: '/offline-demo'
      path: '/offline-demo'
      fullPath: '/offline-demo'
      preLoaderRoute: typeof OfflineDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caja': {
      id: '/caja'
      path: '/caja'
      fullPath: '/caja'
      preLoaderRoute: typeof CajaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventas/detalle': {
      id: '/ventas/detalle'
      path: '/detalle'
      fullPath: '/ventas/detalle'
      preLoaderRoute: typeof VentasDetalleRouteImport
      parentRoute: typeof VentasRoute
    }
    '/inventario/nuevo': {
      id: '/inventario/nuevo'
      path: '/nuevo'
      fullPath: '/inventario/nuevo'
      preLoaderRoute: typeof InventarioNuevoRouteImport
      parentRoute: typeof InventarioRoute
    }
  }
}

interface InventarioRouteChildren {
  InventarioNuevoRoute: typeof InventarioNuevoRoute
}

const InventarioRouteChildren: InventarioRouteChildren = {
  InventarioNuevoRoute: InventarioNuevoRoute,
}

const InventarioRouteWithChildren = InventarioRoute._addFileChildren(
  InventarioRouteChildren,
)

interface VentasRouteChildren {
  VentasDetalleRoute: typeof VentasDetalleRoute
}

const VentasRouteChildren: VentasRouteChildren = {
  VentasDetalleRoute: VentasDetalleRoute,
}

const VentasRouteWithChildren =
  VentasRoute._addFileChildren(VentasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  CajaRoute: CajaRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  DashboardRoute: DashboardRoute,
  InventarioRoute: InventarioRouteWithChildren,
  LoginRoute: LoginRoute,
  OfflineDemoRoute: OfflineDemoRoute,
  ReportesRoute: ReportesRoute,
  SincronizacionRoute: SincronizacionRoute,
  SoporteRoute: SoporteRoute,
  VentasRoute: VentasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
